=== mahd3d/mahd3d/data/json/objects.schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://example.com/object1602852176.json",
  "title": "Root",
  "type": "object",
  "required": [
    "unit",
    "z_ceil",
    "z_sat",
    "z_marker",
    "layers",
    "optimize",
    "marker_grid",
    "sat_grid"
  ],
  "properties": {
    "unit": {
      "$id": "#root/unit",
      "title": "Unit",
      "type": "string",
      "default": "",
      "examples": [
        "m"
      ],
      "pattern": "^.*$"
    },
    "z_ceil": {
      "$id": "#root/z_ceil",
      "title": "Z_ceil",
      "type": "integer",
      "examples": [
        5
      ],
      "default": 0
    },
    "z_sat": {
      "$id": "#root/z_sat",
      "title": "Z_sat",
      "type": "number",
      "examples": [
        4.5
      ],
      "default": 0.0
    },
    "z_marker": {
      "$id": "#root/z_marker",
      "title": "Z_marker",
      "type": "integer",
      "examples": [
        1
      ],
      "default": 0
    },
    "layers": {
      "$id": "#root/layers",
      "title": "Layers",
      "type": "array",
      "default": [],
      "items": {
        "$id": "#root/layers/items",
        "title": "Items",
        "type": "object",
        "required": [
          "points",
          "height",
          "shape_type",
          "shapeId"
        ],
        "properties": {
          "points": {
            "$id": "#root/layers/items/points",
            "title": "Points",
            "type": "array",
            "default": [],
            "items": {
              "$id": "#root/layers/items/points/items",
              "title": "Items",
              "type": "object",
              "required": [
                "x",
                "y",
                "id"
              ],
              "properties": {
                "x": {
                  "$id": "#root/layers/items/points/items/x",
                  "title": "X",
                  "type": "number",
                  "examples": [
                    0.03
                  ],
                  "default": 0.0
                },
                "y": {
                  "$id": "#root/layers/items/points/items/y",
                  "title": "Y",
                  "type": "number",
                  "examples": [
                    8.61
                  ],
                  "default": 0.0
                },
                "id": {
                  "$id": "#root/layers/items/points/items/id",
                  "title": "Id",
                  "type": "integer",
                  "examples": [
                    1
                  ],
                  "default": 0
                }
              }
            }
          },
          "height": {
            "$id": "#root/layers/items/height",
            "title": "Height",
            "type": "number",
            "examples": [
              2.8
            ],
            "default": 0.0
          },
          "shape_type": {
            "$id": "#root/layers/items/shape_type",
            "title": "Shape_type",
            "type": "string",
            "default": "",
            "examples": [
              "obstacle"
            ],
            "pattern": "^.*$"
          },
          "shapeId": {
            "$id": "#root/layers/items/shapeId",
            "title": "Shapeid",
            "type": "string",
            "default": "",
            "examples": [
              "166b0deb-087b-4cad-a102-eaa686067acc"
            ],
            "pattern": "^.*$"
          }
        }
      }
    },
    "optimize": {
      "$id": "#root/optimize",
      "title": "Optimize",
      "type": "boolean",
      "examples": [
        true
      ],
      "default": true
    },
    "marker_grid": {
      "$id": "#root/marker_grid",
      "title": "Marker_grid",
      "type": "integer",
      "examples": [
        1
      ],
      "default": 0
    },
    "sat_grid": {
      "$id": "#root/sat_grid",
      "title": "Sat_grid",
      "type": "integer",
      "examples": [
        10
      ],
      "default": 0
    }
  }
}

=== mahd3d/mahd3d/data/json/objects.example.json
{
  "unit": "m",
  "z_ceil": 5,
  "z_sat": 4.5,
  "z_marker": 1,
  "layers": [
    {
      "points": [
        {
          "x": 0.03,
          "y": 8.61,
          "id": 1
        },
        {
          "x": 0.97,
          "y": 8.61,
          "id": 2
        },
        {
          "x": 0.97,
          "y": 5.26,
          "id": 3
        },
        {
          "x": 0.03,
          "y": 5.26,
          "id": 4
        }
      ],
      "height": 2.8,
      "shape_type": "obstacle",
      "shapeId": "166b0deb-087b-4cad-a102-eaa686067acc"
    },
    {
      "points": [
        {
          "x": -0.1,
          "y": 1.22,
          "id": 1
        },
        {
          "x": 0.9,
          "y": 1.22,
          "id": 2
        },
        {
          "x": 0.9,
          "y": 4.4,
          "id": 3
        },
        {
          "x": -0.1,
          "y": 4.4,
          "id": 4
        }
      ],
      "height": 2.8,
      "shape_type": "obstacle",
      "shapeId": "b2075101-2f5a-447b-be4d-bfea7a405119"
    },
    {
      "points": [
        {
          "x": 3.1,
          "y": 0.85,
          "id": 1
        },
        {
          "x": 4.54,
          "y": 0.85,
          "id": 2
        },
        {
          "x": 4.54,
          "y": 2.29,
          "id": 3
        },
        {
          "x": 3.1,
          "y": 2.29,
          "id": 4
        }
      ],
      "height": 2.8,
      "shape_type": "obstacle",
      "shapeId": "b56c3cca-911f-442c-ab1f-b808ebfed5ec"
    },
    {
      "points": [
        {
          "x": 7.73,
          "y": 0.69,
          "id": 1
        },
        {
          "x": 11.46,
          "y": 0.69,
          "id": 2
        },
        {
          "x": 11.46,
          "y": 2.32,
          "id": 3
        },
        {
          "x": 7.73,
          "y": 2.32,
          "id": 4
        }
      ],
      "height": 2.8,
      "shape_type": "obstacle",
      "shapeId": "6300ee7c-c9da-438c-b8a8-38a60f5a5137"
    },
    {
      "points": [
        {
          "x": 11.46,
          "y": 6.73,
          "id": 1
        },
        {
          "x": 13.430000000000001,
          "y": 6.73,
          "id": 2
        },
        {
          "x": 13.430000000000001,
          "y": 8.26,
          "id": 3
        },
        {
          "x": 11.46,
          "y": 8.26,
          "id": 4
        }
      ],
      "height": 2.8,
      "shape_type": "obstacle",
      "shapeId": "5a772823-7fd5-4205-a530-3321719a4269"
    },
    {
      "points": [
        {
          "x": -0.3,
          "y": 11.87,
          "id": 1
        },
        {
          "x": 0.39999999999999997,
          "y": 11.87,
          "id": 2
        },
        {
          "x": 0.39999999999999997,
          "y": 13.62,
          "id": 3
        },
        {
          "x": -0.3,
          "y": 13.62,
          "id": 4
        }
      ],
      "height": 5,
      "shape_type": "obstacle",
      "shapeId": "3056d1b8-877c-436f-ab73-794b5f1539ee"
    },
    {
      "points": [
        {
          "x": 2.5,
          "y": 13.81,
          "id": 1
        },
        {
          "x": 8.26,
          "y": 13.81,
          "id": 2
        },
        {
          "x": 8.26,
          "y": 15.120000000000001,
          "id": 3
        },
        {
          "x": 2.5,
          "y": 15.120000000000001,
          "id": 4
        }
      ],
      "height": 3.5,
      "shape_type": "obstacle",
      "shapeId": "37aedceb-b351-47fd-a5c1-411c283232cf"
    },
    {
      "points": [
        {
          "x": 18.5,
          "y": 17.47,
          "id": 1
        },
        {
          "x": 19.94,
          "y": 17.47,
          "id": 2
        },
        {
          "x": 19.94,
          "y": 20.04,
          "id": 3
        },
        {
          "x": 18.5,
          "y": 20.04,
          "id": 4
        }
      ],
      "height": 4,
      "shape_type": "obstacle",
      "shapeId": "df719cfb-fccd-4191-97da-bdc742178607"
    },
    {
      "points": [
        {
          "x": 16.34,
          "y": 14.53,
          "id": 1
        },
        {
          "x": 17.94,
          "y": 14.53,
          "id": 2
        },
        {
          "x": 17.94,
          "y": 16.099999999999998,
          "id": 3
        },
        {
          "x": 16.34,
          "y": 16.099999999999998,
          "id": 4
        }
      ],
      "height": 3,
      "shape_type": "obstacle",
      "shapeId": "1b3ba782-2f91-4f43-9460-479e066efb5d"
    },
    {
      "points": [
        {
          "x": 17.16,
          "y": 16.12,
          "id": 1
        },
        {
          "x": 17.57,
          "y": 16.12,
          "id": 2
        },
        {
          "x": 17.57,
          "y": 18.94,
          "id": 3
        },
        {
          "x": 17.16,
          "y": 18.94,
          "id": 4
        }
      ],
      "height": 3,
      "shape_type": "obstacle",
      "shapeId": "697a4ed5-c77b-47c5-9fcd-dc8813cb4be2"
    },
    {
      "points": [
        {
          "x": 19.51,
          "y": 3.1,
          "id": 1
        },
        {
          "x": 25.740000000000002,
          "y": 3.1,
          "id": 2
        },
        {
          "x": 25.740000000000002,
          "y": 6.73,
          "id": 3
        },
        {
          "x": 19.51,
          "y": 6.73,
          "id": 4
        }
      ],
      "height": 2,
      "shape_type": "obstacle",
      "shapeId": "484629f8-4933-4856-b73c-d326fbfa5967"
    },
    {
      "points": [
        {
          "x": 32.75,
          "y": 0.66,
          "id": 1
        },
        {
          "x": 37.32,
          "y": 0.66,
          "id": 2
        },
        {
          "x": 37.32,
          "y": 2.73,
          "id": 3
        },
        {
          "x": 32.75,
          "y": 2.73,
          "id": 4
        }
      ],
      "height": 4.5,
      "shape_type": "obstacle",
      "shapeId": "da435c45-36e9-4d6c-9a04-7e2fa532afde"
    },
    {
      "points": [
        {
          "x": 42.05,
          "y": 3.07,
          "id": 1
        },
        {
          "x": 43.239999999999995,
          "y": 3.07,
          "id": 2
        },
        {
          "x": 43.239999999999995,
          "y": 7.01,
          "id": 3
        },
        {
          "x": 42.05,
          "y": 7.01,
          "id": 4
        }
      ],
      "height": 2.3,
      "shape_type": "obstacle",
      "shapeId": "0c412f88-0096-495a-8a66-4a3399eed6df"
    },
    {
      "points": [
        {
          "x": 38.85,
          "y": 1.16,
          "id": 1
        },
        {
          "x": 47.02,
          "y": 1.16,
          "id": 2
        },
        {
          "x": 47.02,
          "y": 2.96,
          "id": 3
        },
        {
          "x": 38.85,
          "y": 2.96,
          "id": 4
        }
      ],
      "height": 3,
      "shape_type": "obstacle",
      "shapeId": "fad6a626-f56a-4e19-a16d-b658e0e4481e"
    },
    {
      "points": [
        {
          "x": 16.53,
          "y": 5.64,
          "id": 1
        },
        {
          "x": 16.060000000000002,
          "y": 5.64,
          "id": 2
        },
        {
          "x": 16.060000000000002,
          "y": 0.040000000000000036,
          "id": 3
        },
        {
          "x": 16.53,
          "y": 0.040000000000000036,
          "id": 4
        }
      ],
      "height": 2,
      "shape_type": "obstacle",
      "shapeId": "209f060f-de8d-4407-bb87-993c773952b5"
    },
    {
      "points": [
        {
          "x": 30.81,
          "y": 17.44,
          "id": 1
        },
        {
          "x": 40.58,
          "y": 17.44,
          "id": 2
        },
        {
          "x": 40.58,
          "y": 18.290000000000003,
          "id": 3
        },
        {
          "x": 30.81,
          "y": 18.290000000000003,
          "id": 4
        }
      ],
      "height": 1.7,
      "shape_type": "obstacle",
      "shapeId": "96a6adc5-15c8-409a-bf55-4e005cacba95"
    },
    {
      "points": [
        {
          "x": 29.21,
          "y": 17.82,
          "id": 1
        },
        {
          "x": 30.490000000000002,
          "y": 17.82,
          "id": 2
        },
        {
          "x": 30.490000000000002,
          "y": 22.36,
          "id": 3
        },
        {
          "x": 29.21,
          "y": 22.36,
          "id": 4
        }
      ],
      "height": 2,
      "shape_type": "obstacle",
      "shapeId": "d5e6332b-d18a-48e6-abe6-db678bb1c5db"
    },
    {
      "points": [
        {
          "x": 25.58,
          "y": 22.32,
          "id": 1
        },
        {
          "x": 34.03,
          "y": 22.32,
          "id": 2
        },
        {
          "x": 34.03,
          "y": 23.82,
          "id": 3
        },
        {
          "x": 25.58,
          "y": 23.82,
          "id": 4
        }
      ],
      "height": 2,
      "shape_type": "obstacle",
      "shapeId": "66069ed1-bd02-480b-b264-323dad5d274a"
    },
    {
      "points": [
        {
          "x": 25.02,
          "y": 14.62,
          "id": 1
        },
        {
          "x": 24.93,
          "y": 14.62,
          "id": 2
        },
        {
          "x": 24.93,
          "y": 24.14,
          "id": 3
        },
        {
          "x": 25.02,
          "y": 24.14,
          "id": 4
        }
      ],
      "height": 2,
      "shape_type": "obstacle",
      "shapeId": "386176e7-19cb-46a2-9d7f-cbbd241163b7"
    },
    {
      "points": [
        {
          "x": 0,
          "y": 0,
          "id": 1
        },
        {
          "x": 54.27,
          "y": 0,
          "id": 2
        },
        {
          "x": 54.27,
          "y": 24.33,
          "id": 3
        },
        {
          "x": 0,
          "y": 24.33,
          "id": 4
        }
      ],
      "height": 5,
      "shape_type": "wall",
      "shapeId": "b12d4e9c-d68f-4877-8396-d916d6c0bfc6"
    }
  ],
  "optimize": true,
  "marker_grid": 1,
  "sat_grid": 10
}
